version: "3.9"
services:
    web-server:
        image: nginx:1.21.1
        container_name: app-server
        ports:
            - "80:80"
        # - "443:443"
        networks:
            - web-dev
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/server/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            dockerfile: docker/php.dockerfile
            context: .
        user: "1000:1000"
        image: app:latest
        container_name: app
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - web-dev

    mariadb:
        container_name: mariadb
        image: 'mariadb:10'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
        volumes:
            - db-data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
        networks:
            - web-dev

networks:
    web-dev:
        driver: bridge

volumes:
    web-server:
    php:
    db-data:
        driver: local
